quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

quarkus.mongodb.database=${MONGODB_DATABASE_NAME}
quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING}

quarkus.http.host=0.0.0.0
quarkus.http.port=8080
